### ISSUE TITLE
Compatibility Issue with TensorRT 10.0.1.6 and Python Serialization

### ISSUE THREAD

**Issue by Liu-Jinxin** [spacewalk01/depth-anything-tensorrt#36]
HI, thanks for your work, I am encountering an issue while trying to test the exported model using TensorRT version 10.0.1.6. The following error occurs, which seems to be related to model serialization:
```
/workspace/depth_refinement/depth-anything-tensorrt$ python python/trt_infer.py --engine depth_anything_v2_vitl.engine --img Depth-Anything-V2/assets/examples/demo01.jpg --outdir Depth-Anything-V2/results
[06/24/2024-08:09:57] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.Trying to load an engine created with incompatible serialization version. Check that the engine was not created using safety runtime, same OS was used and version compatibility parameters were set accordingly.)
Traceback (most recent call last):
  File "/workspace/depth_refinement/depth-anything-tensorrt/python/trt_infer.py", line 61, in <module>
    run(args)
  File "/workspace/depth_refinement/depth-anything-tensorrt/python/trt_infer.py", line 20, in run
    with engine.create_execution_context() as context:
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
I am not sure if the issue stems from how the model is exported or if there might be a compatibility issue with Python. Any insights or suggestions on how to address this problem would be greatly appreciated.

Thank you!

**Comment by spacewalk01** [comment]
I haven't upgraded python version for tensorrt10. I will look into it.

**Comment by Liu-Jinxin** [comment]
Thank you for your prompt response! I'm not entirely sure if the issues I'm encountering are due to misconfigurations in my environment or if they stem from the current Python version support for TensorRT 10 being incomplete. I look forward to any updates you might provide on this matter.

**Comment by LWQ2EDU** [comment]
> HI, thanks for your work, I am encountering an issue while trying to test the exported model using TensorRT version 10.0.1.6. The following error occurs, which seems to be related to model serialization:
> 
> ```
> /workspace/depth_refinement/depth-anything-tensorrt$ python python/trt_infer.py --engine depth_anything_v2_vitl.engine --img Depth-Anything-V2/assets/examples/demo01.jpg --outdir Depth-Anything-V2/results
> [06/24/2024-08:09:57] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.Trying to load an engine created with incompatible serialization version. Check that the engine was not created using safety runtime, same OS was used and version compatibility parameters were set accordingly.)
> Traceback (most recent call last):
>   File "/workspace/depth_refinement/depth-anything-tensorrt/python/trt_infer.py", line 61, in <module>
>     run(args)
>   File "/workspace/depth_refinement/depth-anything-tensorrt/python/trt_infer.py", line 20, in run
>     with engine.create_execution_context() as context:
> AttributeError: 'NoneType' object has no attribute 'create_execution_context'
> ```
> 
> I am not sure if the issue stems from how the model is exported or if there might be a compatibility issue with Python. Any insights or suggestions on how to address this problem would be greatly appreciated.
> 
> Thank you!

Have you checked the variables of “engine”？
