### ISSUE TITLE
DepthAnythingTensorrt' object has no attribute 'engine_label

### ISSUE THREAD

**Issue by Arctecdev** [spacewalk01/depth-anything-tensorrt#39]
I have an Error with the node/ engine
I reinstalled Depth Anything Tensorrt 3 times and generated the engine files and have put them into the folder..

This error remains...

Can anyone help?

Greetz Johannes

**Comment by spacewalk01** [comment]
Hi Will you share full error message?

**Comment by jilt** [comment]
got the very same error here, I did export the engine and follow instructions for installing, these are the console logs:

```got prompt
!!! Exception during processing !!! 'DepthAnythingTensorrt' object has no attribute 'engine_label'
Traceback (most recent call last):
  File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depth-Anything-Tensorrt\__init__.py", line 29, in main
    if (not hasattr(self, 'engine') or self.engine_label != engine):
                                       ^^^^^^^^^^^^^^^^^
AttributeError: 'DepthAnythingTensorrt' object has no attribute 'engine_label'

Prompt executed in 0.01 seconds```

**Comment by jilt** [comment]
> got the very same error here, I did export the engine and follow instructions for installing, these are the console logs:
> 
> ```
> !!! Exception during processing !!! 'DepthAnythingTensorrt' object has no attribute 'engine_label'
> Traceback (most recent call last):
>   File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\sdxl\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depth-Anything-Tensorrt\__init__.py", line 29, in main
>     if (not hasattr(self, 'engine') or self.engine_label != engine):
>                                        ^^^^^^^^^^^^^^^^^
> AttributeError: 'DepthAnythingTensorrt' object has no attribute 'engine_label'
> 
> Prompt executed in 0.01 seconds```
> ```

some additional info from ComfyUI when i ry to run the workflow again:

`'DepthAnythingTensorrt' object has no attribute 'engine_label'`

This is the workflow
```
{"last_node_id":17,"last_link_id":17,"nodes":[{"id":14,"type":"VAEDecode","pos":[604.9806518554688,192.13693237304688],"size":[210,46],"flags":{},"order":0,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":null},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":null}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":1,"type":"LoadImage","pos":[-1053.9832763671875,-219.18894958496094],"size":[315,314],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_temp_njfth_00005_.png","image"]},{"id":8,"type":"ControlNetApplyAdvanced","pos":[54.01637649536133,278.65167236328125],"size":[315,186],"flags":{},"order":11,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":13},{"name":"control_net","type":"CONTROL_NET","link":12},{"name":"image","type":"IMAGE","link":14},{"name":"vae","type":"VAE","link":15,"shape":7}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[5],"slot_index":0},{"name":"negative","type":"CONDITIONING","links":[6],"slot_index":1}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[1,0,1]},{"id":16,"type":"EmptyLatentImage","pos":[64.64112091064453,594.3560180664062],"size":[315,106],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[3]}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":6,"type":"KSampler","pos":[573.106689453125,0.8931449055671692],"size":[315,262],"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":2},{"name":"positive","type":"CONDITIONING","link":5},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":3}],"outputs":[{"name":"LATENT","type":"LATENT","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[623460885294362,"randomize",1,1,"lcm","normal",1]},{"id":17,"type":"VAEDecode","pos":[1032.929931640625,-4.225093841552734],"size":[210,46],"flags":{},"order":13,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":9},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[10],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":15,"type":"PreviewImage","pos":[1488.647216796875,-88.3068618774414],"size":[210,26],"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":10}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":13,"type":"TorchCompileLoadVAE","pos":[561.7933349609375,-270.15472412109375],"size":[315,154],"flags":{},"order":8,"mode":0,"inputs":[{"name":"vae","type":"VAE","link":7}],"outputs":[{"name":"VAE","type":"VAE","links":[8],"slot_index":0}],"properties":{"Node name for S&R":"TorchCompileLoadVAE"},"widgets_values":["inductor",false,"default",true,true]},{"id":7,"type":"ControlNetLoader","pos":[-847.5614624023438,204.27935791015625],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[11],"slot_index":0}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["control_v11f1p_sd15_depth_fp16.safetensors"]},{"id":9,"type":"TorchCompileLoadControlNet","pos":[-441.7547302246094,163.29852294921875],"size":[327.5999755859375,106],"flags":{},"order":7,"mode":0,"inputs":[{"name":"controlnet","type":"CONTROL_NET","link":11}],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[12],"slot_index":0}],"properties":{"Node name for S&R":"TorchCompileLoadControlNet"},"widgets_values":["inductor",false,"default"]},{"id":11,"type":"VAELoader","pos":[-461.4307861328125,-243.25555419921875],"size":[315,58],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[7,15],"slot_index":0}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["vae-ft-ema-560000-ema-pruned.safetensors"]},{"id":3,"type":"CheckpointLoaderSimple","pos":[-1175.2689208984375,349.85064697265625],"size":[315,98],"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[2]},{"name":"CLIP","type":"CLIP","links":[16,17],"slot_index":1},{"name":"VAE","type":"VAE","links":null}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["dreamshaper_8.safetensors"]},{"id":5,"type":"CLIPTextEncode","pos":[-510.6080322265625,345.4354248046875],"size":[400,200],"flags":{},"order":9,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":16}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""]},{"id":4,"type":"CLIPTextEncode","pos":[-507.02044677734375,602.2206420898438],"size":[400,200],"flags":{},"order":10,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":17}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[13],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["the hulk"]},{"id":2,"type":"DepthAnythingTensorrt","pos":[-455.0010070800781,-107.2851791381836],"size":[315,58],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[14],"slot_index":0}],"properties":{"Node name for S&R":"DepthAnythingTensorrt"},"widgets_values":["depth_anything_v2_vitb_fp16.safetensors"]}],"links":[[1,1,0,2,0,"IMAGE"],[2,3,0,6,0,"MODEL"],[3,16,0,6,3,"LATENT"],[4,5,0,8,0,"CONDITIONING"],[5,8,0,6,1,"CONDITIONING"],[6,8,1,6,2,"CONDITIONING"],[7,11,0,13,0,"VAE"],[8,13,0,17,1,"VAE"],[9,6,0,17,0,"LATENT"],[10,17,0,15,0,"IMAGE"],[11,7,0,9,0,"CONTROL_NET"],[12,9,0,8,2,"CONTROL_NET"],[13,4,0,8,1,"CONDITIONING"],[14,2,0,8,3,"IMAGE"],[15,11,0,8,4,"VAE"],[16,3,1,5,0,"CLIP"],[17,3,1,4,0,"CLIP"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7247295000000024,"offset":[1589.189459095636,438.47173495439984]},"VHS_latentpreview":false,"VHS_latentpreviewrate":0},"version":0.4}
```
